### PR TITLE
Add Coalesce functionality

### PR DESCRIPTION
**Pull request by alexgurau**
I also have my own repository with the functionality that I added here.
However, it is better to keep all these in one place and I'm happy if that place is icza/gog.

### CODE REVIEW

**Comment by icza** [comment]
What version of Go are you using? Your code doesn't compile using go1.20.4, you can also check on the [Go Playground](https://go.dev/play/p/7WZGl9vMu94):

    Error: ./gog.go:30:11: invalid operation: v != nil (mismatched types T and untyped nil)

**Comment by icza** [comment]
Anyway, the task can be solved without reflection, so I added the optimal solution: [`gog.Coalesce()`](https://pkg.go.dev/github.com/icza/gog#Coalesce):

```
// Coalesce returns the first non-zero value from listed arguments.
// Returns the zero value of the type parameter if no arguments are given or all are the zero value.
// Useful when you want to initialize a variable to the first non-zero value from a list of fallback values.
//
// For example:
//
//	hostVal := Coalesce(hostName, os.Getenv("HOST"), "localhost")
func Coalesce[T comparable](values ...T) (v T) {
	var zero T
	for _, v = range values {
		if v != zero {
			return
		}
	}
	return
}
```

**Comment by icza** [comment]
Closing this PR without merging.

**Comment by alexgurau** [comment]
Thanks for the feedback, I recently switched to Go and still have some things to learn.
I used go1.20.4 but for what it's worth, the original version had no generic template in its definition, it was something like this:
```
func Coalesce(values ...any) (v any) {
	for _, v = range values {
		if v != nil && !reflect.ValueOf(v).IsZero() {
			break
		}
	}

	return
}
```
I added the template last minute to make it more in line with the purpose of your package and didn't test it properly.

Just one small detail, the alternative that you proposed will not return the last zero value from the argument list if all are zero values, it seems to return the zero value corresponding to the first variable type evaluated in the argument list.

I'm taking all your notes into account, using comparable and also try to avoid reflection and see if I can come up with something better.

**Comment by icza** [comment]
When the generic function is instantiated, the type parameter is substituted with a concrete type. This means all parameters must be of the same type. This may be a restriction, but in practice it's OK. You don't want to initialize a `string` variable with an `int` for example...

Given that, there is no difference between the zero value of any element or the type itself, it's one and the same. This is mentioned in the doc:

> Returns the zero value of the type parameter if no arguments are given or all are the zero value.

**Pull request closed without merging**
